### ISSUE TITLE
Replace registry_key with reg.exe

### ISSUE THREAD

**Issue by dhoer** [dhoer/chef-ie#1]
While Chef's registry_key is great for configuring a current user that the chef-client is running as, it falls down when it comes to configuring default settings for new users and configuring existing users.  To do that, you need to update the appropriate user's hive file `ntuser.dat`. 

The Windows way is to use `regedt32.exe` application and "load hive" menu option to load the file into a registry key and then edit that key, then unload the hive again. But if you want to do it from a script or command line, you need the `reg.exe` command line utility. 

Step 1 - Load User Registry Hive
`reg.exe load HKCU\{username} c:\users\{username}\ntuser.dat`

Step 2 - Make a normal .reg file and import it 
`reg.exe import "update.reg"`

Step 3 - Commit and Unload User Registry Hive 
`reg.exe unload HKCU\{username}`

This approach can be wrapped in a LWRP that would take a .reg.erb template file.

```
windows_reg 'config_ie_for_selenium' do
  source 'selenium.reg.erb'
  cookbook 'ie'
  users ['selenium']
  variables(
    local_home: node['ie]['zone']['local_home']
    ...
  )
end
```

**Comment by mhemesath** [comment]
+1 This would be useful. Currently my selenium user is not my chef user so I need to set some of these settings manually.

**Comment by dhoer** [comment]
This might be a better approach https://sherwoodbase.wordpress.com/2013/02/15/how-to-add-hkcu-keys-and-values-for-all-the-users-with-chef/

**Comment by dhoer** [comment]
http://www.itninja.com/blog/view/appdeploy-articles-activesetup
