### ISSUE TITLE
Update ie_version to support older versions.

### ISSUE THREAD

**Issue by mhemesath** [dhoer/chef-ie#2]
I think we need to update the ie_version function to look for the key name of `Version` in addition to `svcVersion`. See: http://support.microsoft.com/en-us/kb/969393

``` ruby
def ie_version
  return unless platform_family?('windows')
  registry_get_values('HKLM\SOFTWARE\Microsoft\Internet Explorer').each do |value|
    return value[:data] if value[:name] == 'svcVersion' || value[:name] == 'Version'
  end
  ''
end
```

**Comment by dhoer** [comment]
Thanks, I think we would have to loop twice to ensure svcVersion is always returned first and if not found, then return Version.

**Comment by mhemesath** [comment]
Good point
