### ISSUE TITLE
Add ability set zoom level

### ISSUE THREAD

**Issue by mhemesath** [dhoer/chef-ie#3]
Selenium requires the zoom level of IE to be set to 100%. It would be nice to be able to set this in the recipe. A quick search reveals this is possible with this key

``` sh
HKEY_CURRENT_USER\Software\Microsoft\Internet Explorer\Zoom
```

I can add this enhancement if you think its worthwhile.

**Comment by dhoer** [comment]
Sure just call the recipe zoom.rb.  I have not been successful with getting
HKCU keys to update on the first client run.  I'm hoping that the reg.exe
cookbook will take care of it.  But I haven't started work on it yet.

**Comment by mhemesath** [comment]
Gotcha, I read over your issue and it makes little sense to me as I have hardly any windows experience. I'll try to get this recipe created though and it should be straightforward to port it over once you're done.

**Comment by dhoer** [comment]
Thanks.  Basically, IE is not configured after being provisioned by chef
client run (e.g., Protected Mode settings for each zone are not the same
value).  So running 'chef-client -o recipe[ie::security_zones]' fixes the
issue on that machine.  Why it doesn't work on the first chef-client run
for Administrator user is beyond my knowledge.
